---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: core-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app.opennms.org/component: core
    {{- include "core.labels" . | nindent 4 }}
data:
  POSTGRES_USER: {{ .Values.postgresql.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  OPENNMS_DBUSER: {{ .Values.postgresql.opennmsDbUser | b64enc | quote }}
  OPENNMS_DBPASS: {{ .Values.postgresql.opennmsDbPassword | b64enc | quote }}
