apiVersion: v1
kind: Service
metadata:
  name: {{ include "core.fullname" . }}
  labels:
    app.opennms.org/component: core
    {{- include "core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webui
      port: {{ .Values.service.webui.port }}
      targetPort: webui
      protocol: TCP
    - name: karaf
      port: {{ .Values.service.karaf.port }}
      targetPort: karaf
      protocol: TCP
  selector:
    {{- include "core.selectorLabels" . | nindent 4 }}
