---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "core.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.opennms.org/component: core
    {{- include "core.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  serviceName: {{ include "core.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "core.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          args:
              - -i
          envFrom:
            - configMapRef:
                name: core-configmap
            - secretRef:
                name: core-credentials
          volumeMounts:
            # Core configuration directory (Required for production)
            - name: core-etc
              mountPath: /opt/opennms/etc
      containers:
        - name: {{ .Chart.Name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          args:
            - -f
          envFrom:
            - configMapRef:
                name: core-configmap
            - secretRef:
                name: core-credentials
          ports:
            - name: webui
              containerPort: 8980
              protocol: TCP
            - name: karaf
              containerPort: 8101
              protocol: TCP
          volumeMounts:
            # Core configuration directory (Required for production)
            - name: core-etc
              mountPath: /opt/opennms/etc
            # Persistence of requisition cache
            - name: core-etc-imports
              mountPath: /opt/opennms/etc/imports
            # Persistence of detectors and policies for requisitions
            - name: core-etc-foreign-source
              mountPath: /opt/opennms/etc/foreign-source
            # Peristence of RRD, reports and MIBS
            - name: core-data
              mountPath: /opennms-data
            {{- if .Values.persistence.karDeploy.enabled }}
            # Persistence of a KAR deploy directory
            - name: core-kar-deploy
              mountPath: /opt/opennms/deploy
            {{- end }}
            {{- if .Values.persistence.overlay.enabled }}
            # Overlay directories for easier configuration management
            - name: core-overlay
              mountPath: /opt/opennms-overlay
            {{- end }}
            {{- if .Values.persistence.etcOverlay.enabled }}
            # Overlay for /opt/opennms/etc
            - name: core-etc-overlay
              mountPath: /opt/opennms-etc-overlay
            {{- end }}
            {{- if .Values.persistence.jettyOverlay.enabled }}
            # Overlay for /opt/opennms/jetty/webinf
            - name: core-jetty-webinf-overlay
              mountPath: /opt/opennms-jetty-webinf-overlay
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        # Empty dir volumes for non-persistent overlays (if persistence is disabled)
        {{- if not .Values.persistence.karDeploy.enabled }}
        - name: core-kar-deploy
          emptyDir: {}
        {{- end }}
        {{- if not .Values.persistence.overlay.enabled }}
        - name: core-overlay
          emptyDir: {}
        {{- end }}
        {{- if not .Values.persistence.etcOverlay.enabled }}
        - name: core-etc-overlay
          emptyDir: {}
        {{- end }}
        {{- if not .Values.persistence.jettyOverlay.enabled }}
        - name: core-jetty-webinf-overlay
          emptyDir: {}
        {{- end }}
  volumeClaimTemplates:
    # Persistence of data directory (RRD, reports, MIBS)
    - metadata:
        name: core-data
        labels:
          {{- include "core.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.data.storageClass }}
        storageClassName: {{ .Values.persistence.data.storageClass | quote }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.data.accessMode | default "ReadWriteOnce" | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.data.size | default "50Gi" | quote }}
    # Persistence of configuration directory
    - metadata:
        name: core-etc
        labels:
          {{- include "core.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.etc.storageClass }}
        storageClassName: {{ .Values.persistence.etc.storageClass | quote }}
        {{- end }}
        accessModes:
            - {{ .Values.persistence.etc.accessMode | default "ReadWriteOnce" | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.etc.size | default "500Mi" | quote }}
    # Persistence of requisition cache
    - metadata:
        name: core-etc-imports
        labels:
          {{- include "core.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.etcImports.storageClass }}
        storageClassName: {{ .Values.persistence.etcImports.storageClass | quote }}
        {{- end }}
        accessModes:
            - {{ .Values.persistence.etcImports.accessMode | default "ReadWriteOnce" | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.etcImports.size | default "100Mi" | quote }}
    # Persistence of requisition policies and detectors
    - metadata:
        name: core-etc-foreign-source
        labels:
          {{- include "core.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.etcForeignSource.storageClass }}
        storageClassName: {{ .Values.persistence.etcForeignSource.storageClass | quote }}
        {{- end }}
        accessModes:
            - {{ .Values.persistence.etcForeignSource.accessMode | default "ReadWriteOnce" | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.etcForeignSource.size | default "100Mi" | quote }}
    {{- if .Values.persistence.karDeploy.enabled }}
    # Persistence of KAR deploy directory
    - metadata:
        name: core-kar-deploy
        labels:
          {{- include "core.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.karDeploy.storageClass }}
        storageClassName: {{ .Values.persistence.karDeploy.storageClass | quote }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.karDeploy.accessMode | default "ReadWriteOnce" | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.karDeploy.size | default "100Mi" | quote }}
    {{- end }}
    {{- if .Values.persistence.overlay.enabled }}
    # Persistence of etc overlay directory
    - metadata:
        name: core-overlay
        labels:
          {{- include "core.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.overlay.storageClass }}
        storageClassName: {{ .Values.persistence.overlay.storageClass | quote }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.overlay.accessMode | default "ReadWriteOnce" | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.overlay.size | default "100Mi" | quote }}
    {{- end }}
    {{- if .Values.persistence.etcOverlay.enabled }}
    # Persistence of etc-overlay directory
    - metadata:
        name: core-etc-overlay
        labels:
          {{- include "core.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.etcOverlay.storageClass }}
        storageClassName: {{ .Values.persistence.etcOverlay.storageClass | quote }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.etcOverlay.accessMode | default "ReadWriteOnce" | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.etcOverlay.size | default "100Mi" | quote }}
    {{- end }}
    {{- if .Values.persistence.jettyOverlay.enabled }}
    # Persistence of Jetty WEB-INF overlay directory
    - metadata:
        name: core-jetty-webinf-overlay
        labels:
          {{- include "core.labels" . | nindent 10 }}
      spec:
        {{- if .Values.persistence.jettyOverlay.storageClass }}
        storageClassName: {{ .Values.persistence.jettyOverlay.storageClass | quote }}
        {{- end }}
        accessModes:
          - {{ .Values.persistence.jettyOverlay.accessMode | default "ReadWriteOnce" | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.jettyOverlay.size | default "100Mi" | quote }}
    {{- end }}
