# Default values for core.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: docker.io/opennms/horizon
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "bleeding"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

selectorLabels:
  app.opennms.org/component: core

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  type: ClusterIP
  port: 8980
  karaf:
    port: 8101
  webui:
    port: 8980

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  exec:
    command:
      - "pgrep"
      - "java"
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

readinessProbe:
  httpGet:
    port: webui
    path: /opennms/login.jsp
  initialDelaySeconds: 90
  timeoutSeconds: 3
  failureThreshold: 20
  periodSeconds: 5

nodeSelector: {}

tolerations: []

affinity: {}

timezone: UTC
postgresql:
  user: postgres
  password: "Change_Me_Postgres"
  host: cluster-helm-lint-rw.default.svc.cluster.local
  port: 5432
  opennmsDbName: opennms
  opennmsDbUser: opennms_dba
  opennmsDbPassword: "Change_Me_OpenNMS_DBA"

persistence:
  etc:
    storageClass: ""
    size: 500Mi
    accessMode: "ReadWriteOnce"
  etcImports:
    storageClass: ""
    size: 500Mi
    accessMode: "ReadWriteOnce"
  etcForeignSource:
    storageClass: ""
    size: 500Mi
    accessMode: "ReadWriteOnce"
  data:
    storageClass: ""
    size: 5Gi
    accessMode: "ReadWriteOnce"
  karDeploy:
    enabled: false
  overlay:
    enabled: false
  etcOverlay:
    enabled: false
  jettyOverlay:
    enabled: false
