---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: develop-ip4-pool
spec:
  addresses:
    - 192.168.107.245-192.168.107.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: develop-l2-advertisement
spec:
  ipAddressPools:
    - develop-ip4-pool