name: lint and test

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches:
      - '*'
    tags:
      - 'v*'  # Only version tags like v1.0.0

jobs:
  helm-lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: setup helm lint requirements
        uses: ./.github/actions/setup_helmlint
        with:
          create-kind-cluster: "true"

      - name: setup go lang
        uses: ./.github/actions/setup_environment
        with:
          enable_go: true

      - name: run chart-lint
        run: make lint

      - name: run chart-testing (install Core chart)
        run: make install-core

      - name: run chart-testing (install Minion chart)
        run: make install-minion

      - name: run chart-testing (install Sentinel chart)
        run: make install-sentinel